export enum ShopperStatus {
  OFF_DUTY = 'OFF_DUTY', // 근무종료
  RECEIVED_VEHICLE = 'RECEIVED_VEHICLE', // 차량 인수
  WAITING_FOR_RESERVATION = 'WAITING_FOR_RESERVATION', // 예약 대기중
  MOVING_TO_DEPARTURE = 'MOVING_TO_DEPARTURE', // 출발지 이동
  WAITING_FOR_PASSENGER = 'WAITING_FOR_PASSENGER', // 고객 탑승대기
  IN_OPERATION = 'IN_OPERATION', // 운행 중
  WAITING_OPERATION = 'WAITING_OPERATION', // 운행 대기 (경유지에 도착한 경우)
  OPERATION_COMPLETED = 'OPERATION_COMPLETED', // 운행 종료
  PAUSED = 'PAUSED', // 일시정지
}
