name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          # SSH 키 디버깅 (필요시 제거)
          ls -la ~/.ssh/
          cat ~/.ssh/known_hosts

      - name: Debug SSH Connection
        run: |
          # -v 옵션으로 상세 로그 확인
          ssh -v -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "echo SSH 연결 테스트"

      - name: Deploy to EC2
        if: false # 디버깅이 성공한 후에 true로 변경
        run: |
          SSH_COMMAND="ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}"

          # 배포 커맨드 실행
          $SSH_COMMAND "cd ${{ secrets.APP_PATH }} && \
            git pull && \
            pnpm install && \
            pnpm run build && \
            pm2 restart ecosystem.config.js"
